### ISSUE TITLE
Toggler-button does not always work

### ISSUE THREAD

**Issue by violetheath45** [dotnet-presentations/ContosoCrafts#12]
class=”navbar-toggleable-sm” does not exist in Bootstrap, css.
Toggler-button does not always work: my long menu stretches out longer than the navigation
[scr_menuProblem.pdf](https://github.com/dotnet-presentations/ContosoCrafts/files/5031370/scr_menuProblem.pdf)
 bar, header, body and footer (longer than container's/page's width). It is true for ContosoCrafts and any Asp.Net Core web app template. 
In Chrome toggler-button appears, when I re-size to minimum browser window width, in Edge – not at all.
The same is on a phone.
See attached screen-shots, my https://www.violetHeathDesign.com
Any suggestions, please?

**Comment by jamesmontemagno** [comment]
It seems to show up for me, but should be colored white probably

**Comment by jamesmontemagno** [comment]
![image](https://user-images.githubusercontent.com/1676321/151630358-e6b6009a-3969-4bff-a1e6-97fa4c23e39c.png)
