### ISSUE TITLE
Roslyn warning CS8603, Possible null reference return.

### ISSUE THREAD

**Issue by stevenyholm** [dotnet-presentations/ContosoCrafts#16]
I'm following along the videos for this tutorial. I created a new project using Visual Studio 2022. When I copied the contents of JsonFileProductService.cs into my project, this file had a compiler warning #CS8603, "Possible null reference return" on line 28, specifically the part that uses `jsonFileReader.ReadToEnd()`. At this point, I have a few options: 

- Remove the `<Nullable>enable</Nullable>` line from the default csproj file. Notice that this project does not include a Nullable line in it's csproj. 
- Wrap the code in #pragma, like this: 
```
#pragma warning disable CS8603 // Possible null reference return.
                return JsonSerializer.Deserialize<Product[]>(jsonFileReader.ReadToEnd(), new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });
#pragma warning restore CS8603 // Possible null reference return.
```
- Ignore the warning. 

I think the correct call is to remove the nullable line from the csproj, because that will make my code look more like the code in this repo.

**Comment by jamesmontemagno** [comment]
Fixed up :)
